// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _rxbrl_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP xbrlFree(SEXP);
RcppExport SEXP xbrlGetImportNames(SEXP);
RcppExport SEXP xbrlGetLinkbaseNames(SEXP);
RcppExport SEXP xbrlGetSchemaName(SEXP);
RcppExport SEXP xbrlParse(SEXP);
RcppExport SEXP xbrlProcessArcs(SEXP, SEXP);
RcppExport SEXP xbrlProcessContexts(SEXP);
RcppExport SEXP xbrlProcessElements(SEXP);
RcppExport SEXP xbrlProcessFacts(SEXP);
RcppExport SEXP xbrlProcessFootnotes(SEXP);
RcppExport SEXP xbrlProcessLabels(SEXP);
RcppExport SEXP xbrlProcessRoles(SEXP);
RcppExport SEXP xbrlProcessUnits(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_rxbrl_rcpp_hello_world", (DL_FUNC) &_rxbrl_rcpp_hello_world, 0},
    {"xbrlFree",             (DL_FUNC) &xbrlFree,             1},
    {"xbrlGetImportNames",   (DL_FUNC) &xbrlGetImportNames,   1},
    {"xbrlGetLinkbaseNames", (DL_FUNC) &xbrlGetLinkbaseNames, 1},
    {"xbrlGetSchemaName",    (DL_FUNC) &xbrlGetSchemaName,    1},
    {"xbrlParse",            (DL_FUNC) &xbrlParse,            1},
    {"xbrlProcessArcs",      (DL_FUNC) &xbrlProcessArcs,      2},
    {"xbrlProcessContexts",  (DL_FUNC) &xbrlProcessContexts,  1},
    {"xbrlProcessElements",  (DL_FUNC) &xbrlProcessElements,  1},
    {"xbrlProcessFacts",     (DL_FUNC) &xbrlProcessFacts,     1},
    {"xbrlProcessFootnotes", (DL_FUNC) &xbrlProcessFootnotes, 1},
    {"xbrlProcessLabels",    (DL_FUNC) &xbrlProcessLabels,    1},
    {"xbrlProcessRoles",     (DL_FUNC) &xbrlProcessRoles,     1},
    {"xbrlProcessUnits",     (DL_FUNC) &xbrlProcessUnits,     1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rxbrl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
